=== Bahkao/vitam/sources/functional-administration/functional-administration-common/src/main/resources/json-schema/accession-register-summary-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "date-opt-time": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ObjectSize": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "_id": {
      "type": "string"
    },
    "_tenant": {
      "type": "integer"
    },
    "_v": {
      "type": "integer"
    },
    "OriginatingAgency": {
      "type": "string"
    },
    "TotalObjects": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "TotalObjectGroups": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "TotalUnits": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "CreationDate": {
      "$ref": "#/definitions/date-opt-time"
    }
  }
}

=== Bahkao/vitam/sources/functional-administration/functional-administration-rest/src/test/resources/migration_r7_r8/accession_register_summary_EXPECTED.json
[
  {
    "_id": "aefaaaaaaehfvmm5abkceale57asqnqaaaaq",
    "OriginatingAgency": "producteur1",
    "TotalObjects": {
      "ingested": 6,
      "deleted": 0,
      "remained": 6
    },
    "TotalObjectGroups": {
      "ingested": 2,
      "deleted": 0,
      "remained": 2
    },
    "TotalUnits": {
      "ingested": 6,
      "deleted": 0,
      "remained": 6
    },
    "ObjectSize": {
      "ingested": 458720,
      "deleted": 0,
      "remained": 458720
    },
    "CreationDate": "2018-07-31T09:52:50.742",
    "_v": 1,
    "_tenant": 0
  },
  {
    "_id": "aefaaaaaaehfvmm5abkceale57t4p7iaaaaq",
    "OriginatingAgency": "FRAN_NP_009913",
    "TotalObjects": {
      "ingested": 8,
      "deleted": 0,
      "remained": 8
    },
    "TotalObjectGroups": {
      "ingested": 8,
      "deleted": 0,
      "remained": 8
    },
    "TotalUnits": {
      "ingested": 14,
      "deleted": 0,
      "remained": 14
    },
    "ObjectSize": {
      "ingested": 313294,
      "deleted": 0,
      "remained": 313294
    },
    "CreationDate": "2018-07-31T10:35:02.013",
    "_v": 2,
    "_tenant": 0
  }
]

=== Bahkao/vitam/sources/integration-test/src/test/resources/preservation/expected/accession_register_ratp_before.json
[{"_id":"aefaaaaaaabf2a33abbckalhycg6lhaaaaaq","OriginatingAgency":"RATP","TotalObjects":{"ingested":4.0,"deleted":0.0,"remained":4.0},"TotalObjectGroups":{"ingested":3.0,"deleted":0.0,"remained":3.0},"TotalUnits":{"ingested":6.0,"deleted":0.0,"remained":6.0},"ObjectSize":{"ingested":18.0,"deleted":0.0,"remained":18.0},"CreationDate":"2018-12-18T09:03:04.092","_v":1,"_tenant":0}]

=== Bahkao/vitam/sources/functional-administration/functional-administration-common/src/test/resources/accession_register_summary_OK.json
{
  "_id": "aefaaaaaaaed4nrpaas4uak7cxykxiaaaaaq",
	"OriginatingAgency": "Vitam",
	"TotalObjects": {
		"ingested": 292,
		"deleted": 0,
		"remained": 292
	},
	"TotalObjectGroups": {
		"ingested": 138,
		"deleted": 0,
		"remained": 138
	},
	"TotalUnits": {
		"ingested": 201,
		"deleted": 0,
		"remained": 201
	},
	"ObjectSize": {
		"ingested": 35401855,
		"deleted": 0,
		"remained": 35401855
	},
	"CreationDate": "2017-04-12T17:01:11.764",
	"_v": 1,
	"_tenant": 0
}
