=== Bahkao/vitam/sources/functional-administration/functional-administration-common/src/main/resources/json-schema/security-profile-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "_id": {
      "type": "string"
    },
    "_v": {
      "type": "integer"
    },
    "Identifier": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "FullAccess": {
      "type": "boolean"
    },
    "Permissions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "anyOf": [
    {
      "required": ["_id", "_v", "Identifier", "FullAccess", "Permissions", "Name"]
    },
    {
      "required": ["_id", "_v", "Identifier", "FullAccess", "Name"]
    }
  ]
  
}

=== Bahkao/vitam/sources/functional-administration/functional-administration-common/src/test/resources/security_profile_OK.json
{
	"_id": "aegqaaaaaaeucszwabglyak64gjmgbyaaaba",
	"Identifier": "SEC_PROFILE-000002",
	"Name": "demo-security-profile",
	"FullAccess": false,
	"Permissions": [
		"securityprofiles:create",
		"securityprofiles:read",
		"securityprofiles:id:read",
		"securityprofiles:id:update",
		"accesscontracts:read",
		"accesscontracts:id:read",
		"contexts:id:update"
	],
	"_v": 1
}
