=== Bahkao/vitam/sources/common/common-public/src/main/resources/json-schema/accession-register-summary.schema.json
{
  "$schema": "http:\/\/vitam-json-schema.org\/draft-04\/schema#",
  "id": "http:\/\/example.com\/root.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ObjectSize": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        },
        "attached": {
          "type": "number"
        },
        "detached": {
          "type": "number"
        },
        "symbolicRemained": {
          "type": "number"
        }
      }
    },
    "_id": {
      "type": "string"
    },
    "_tenant": {
      "type": "integer"
    },
    "_v": {
      "type": "integer"
    },
    "OriginatingAgency": {
      "type": "string"
    },
    "TotalObjects": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        },
        "attached": {
          "type": "number"
        },
        "detached": {
          "type": "number"
        },
        "symbolicRemained": {
          "type": "number"
        }
      }
    },
    "TotalObjectGroups": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        },
        "attached": {
          "type": "number"
        },
        "detached": {
          "type": "number"
        },
        "symbolicRemained": {
          "type": "number"
        }
      }
    },
    "TotalUnits": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        },
        "attached": {
          "type": "number"
        },
        "detached": {
          "type": "number"
        },
        "symbolicRemained": {
          "type": "number"
        }
      }
    },
    "creationDate": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    }
  }
}

=== Bahkao/vitam/sources/integration-test/src/test/resources/ingestCleanup/accession_register_summary_2_no_cleanup.json
[
  {
    "OriginatingAgency": "Service_producteur",
    "TotalObjects": {
      "ingested": 0.0,
      "deleted": 0.0,
      "remained": 0.0
    },
    "TotalObjectGroups": {
      "ingested": 0.0,
      "deleted": 0.0,
      "remained": 0.0
    },
    "TotalUnits": {
      "ingested": 1.0,
      "deleted": 0.0,
      "remained": 1.0
    },
    "ObjectSize": {
      "ingested": 0.0,
      "deleted": 0.0,
      "remained": 0.0
    },
    "_v": 1,
    "_tenant": 0
  }
]
